services:
  postgres:
    container_name: postgres
    image: postgres:18
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5433:5432'
    volumes:
      - postgres-data:/var/lib/postgresql
    networks:
      - real-time-chat

volumes:
  postgres-data:

networks:
  reat-time-chat:
